---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: centos7
    box: centos7.box
    memory: 512
    cpus: 1  
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        elastic_ip: "10.10.20.19"
        kibana_ip: 10.10.20.20
verifier:
  name: ansible
